#docker-composeのバージョン
version: '3'
services:
  app:
    build: 
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/graduation_work
      - public-data:/graduation_work/public
      - tmp-data:/graduation_work/tmp
      - log-data:/graduation_work/log
    # depends_on:
    #   - db
  # db:
  #   image: postgres
  #   ports:
  #     - '5432:5432' # ホストからゲストへポートフォワード
  #   volumes:
  #     - postgresql-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/graduation_work/public
      - tmp-data:/graduation_work/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgresql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  db-data:
