# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # ローカル使用の際は以下をコメントアウト
  # host: db
  # username: postgres
  # password: password

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graduation_work_development

test:
  <<: *default
  database: graduation_work_test

production:
  <<: *default
  # RDS
  host: <%= ENV.fetch("RDS_HOST") %>
  database: <%= ENV.fetch("RDS_DATABASE") %>
  username: <%= ENV.fetch("RDS_USERNAME") %>
  password: <%= ENV.fetch("RDS_PASSWORD") %>


